### ISSUE TITLE
Daten werden nicht richtig übertragen

### ISSUE THREAD

**Issue by DominikTV** [Theenoro/speedtester#1]
Nach dem Speedtest sieht die Console so aus:

```
C:\test>node index.js
---------------
Sun Oct 22 2017 14:29:29 GMT+0200 (Mitteleuropäische Sommerzeit)
---------------
Start Speedtest
github.com/zpeters/speedtest -- unofficial cli for speedtest.net

Server: 6670 - Cologne (hotspot.koeln)
2017/10/22 14:29:31 Testing download speed

.
2017/10/22 14:30:05 Testing upload speed

.

Ping (Lowest): 32.06 ms | Download (Max): 21.16 Mbps | Upload (Max): 0.70 Mbps

child process exited with code 0
{ download: NaN, upload: 0, ping: 0, time: 1508675471 }
The HTML file was saved!
```
Zu sehen ist das:
![2017-10-22 14_33_38-table](https://user-images.githubusercontent.com/7671638/31861949-11ef9fd8-b736-11e7-896c-71b94adc1e2b.jpg)

(Unter Windows)

**Comment by Theenoro** [comment]
Danke habs leider jetzt erst in den Emails gelesen.
Habe es auch direkt gefixt. Die Windows Version von Speedtest.net CLI gibt einen anderen ausgabewert, deswegen kam das script nicht klar.


FIX: https://github.com/Theenoro/speedtester/commit/17d26cb1bc67da047133abc7bb5651107ef10cf4

ist direkt im Master gepusht
